services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rbac
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
