services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rbac
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"

  infinispan:
    image: quay.io/infinispan/server:latest
    environment:
      USER: admin
      PASS: password
    ports:
      - "11222:11222"
