INSERT INTO sys_permission (create_at, update_at, name, code, resource, action, group_code, description, expression)
VALUES
    (now(), now(), 'View User', 'user:view', 'user', 'view', 'system.user', 'view users', 'user:view'),
    (now(), now(), 'Add User', 'user:add', 'user', 'add', 'system.user', 'add users', 'user:add'),
    (now(), now(), 'Edit User', 'user:edit', 'user', 'edit', 'system.user', 'edit users', 'user:edit'),
    (now(), now(), 'Delete User', 'user:delete', 'user', 'delete', 'system.user', 'delete users', 'user:delete'),
    (now(), now(), 'Assign Role', 'user:assign-role', 'user', 'assign-role', 'system.user', 'assign user roles', 'user:assign-role'),
    (now(), now(), 'Reset Password', 'user:reset-password', 'user', 'reset-password', 'system.user', 'reset user passwords', 'user:reset-password'),
    (now(), now(), 'View Role', 'role:view', 'role', 'view', 'system.role', 'view roles', 'role:view'),
    (now(), now(), 'Add Role', 'role:add', 'role', 'add', 'system.role', 'add roles', 'role:add'),
    (now(), now(), 'Edit Role', 'role:edit', 'role', 'edit', 'system.role', 'edit roles', 'role:edit'),
    (now(), now(), 'Delete Role', 'role:delete', 'role', 'delete', 'system.role', 'delete roles', 'role:delete'),
    (now(), now(), 'Assign Permission Group', 'role:assign-permission-group', 'role', 'assign-permission-group', 'system.role', 'assign permission groups to roles', 'role:assign-permission-group'),
    (now(), now(), 'View Permission', 'permission:view', 'permission', 'view', 'system.permission', 'view permissions', 'permission:view'),
    (now(), now(), 'Edit Permission', 'permission:edit', 'permission', 'edit', 'system.permission', 'edit permissions', 'permission:edit'),
    (now(), now(), 'View Permission Group', 'permission-group:view', 'permission-group', 'view', 'system.permission-group', 'view permission groups', 'permission-group:view'),
    (now(), now(), 'Add Permission Group', 'permission-group:add', 'permission-group', 'add', 'system.permission-group', 'add permission groups', 'permission-group:add'),
    (now(), now(), 'Edit Permission Group', 'permission-group:edit', 'permission-group', 'edit', 'system.permission-group', 'edit permission groups', 'permission-group:edit'),
    (now(), now(), 'Delete Permission Group', 'permission-group:delete', 'permission-group', 'delete', 'system.permission-group', 'delete permission groups', 'permission-group:delete'),
    (now(), now(), 'Assign Permission', 'permission-group:assign-permission', 'permission-group', 'assign-permission', 'system.permission-group', 'assign permissions to groups', 'permission-group:assign-permission'),
    (now(), now(), 'Change Password', 'auth:change-password', 'auth', 'change-password', 'system.auth', 'change own password', 'auth:change-password');
